---
title: "Juma-project_02_b"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---


```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)

# Make some noisily increasing data

data_url <- "../data/WestRoxbury.csv"
west_rox <- read.csv(data_url)
#summary(west_df)
#table(west_df$REMODEL)
#head(west_df)

west_upper <- west_df %>%
  filter(TOTAL.VALUE > 600)

west_lower <- west_df %>%
  filter(TOTAL.VALUE <= 300)

west_old <- west_df %>%
  filter(YR.BUILT < 1985) %>%
  mutate(Re_model = ifelse(REMODEL=='Recent',1,0))

```

geom_point
=======================================================================

Row
-----------------------------------------------------------------------

### General House Value Trend

```{r}
p <- ggplot(west_df, aes(x=GROSS.AREA/10, y=TOTAL.VALUE)) +
            geom_point(aes(color = as.factor(FULL.BATH), size = ROOMS)) +
            geom_smooth(method="loess") +
            scale_color_viridis_d() +
            scale_x_log10(labels=scales::comma) +
            labs(title = "Roxbury Houses: General Trend of Value against Total Area") +
            theme(plot.title = element_text(size = 8, face = "bold", colour = "dodgerblue4"))
ggplotly(p)
```



### Upper Quarter Houses

```{r}
p1 <- ggplot(data = west_upper,
             mapping = aes(x = GROSS.AREA,
                           y = TOTAL.VALUE)) + 
  geom_point(aes(size = FULL.BATH),alpha = 0.4, color = "gray50") +
  geom_point(data = subset(west_upper,
                           LIVING.AREA > 3500 & ROOMS > 5 & FIREPLACE > 0), color = "orange3") +
  scale_x_log10(labels=scales::comma) +
  geom_smooth(method="loess") + 
  labs(title = "Filtered: Rooms > 5 | Living Area > 3500 sq ft | Fireplace = Yes") +
  theme(plot.title = element_text(size = 8, face = "bold", colour = "orange3"))

ggplotly(p1)
```

Row
-----------------------------------------------------------------------

### Lower Quarter Houses

```{r}
p2 <- ggplot(data = west_lower,
             mapping = aes(x = GROSS.AREA,
                           y = TOTAL.VALUE)) + 
  geom_point(aes(size = ROOMS),alpha = 0.15, color = "gray50") +
  geom_point(data = subset(west_lower,
                           FULL.BATH >= 2 & TAX < 4000 & LIVING.AREA <= 2000), color = "red4") +
  scale_x_log10(labels=scales::comma) +
  geom_smooth(method="loess", color = "skyblue3") +
  labs(title = "Filtered: Bathrooms > 2 | Tax < 4000/yr | Living Area <= 2000 sq ft") +
  theme(plot.title = element_text(size = 8, face = "bold", colour = "red4"))

ggplotly(p2)
```

### Old Houses - Year Built prior to 1985

```{r}

p3 <- ggplot(data = west_old,
             mapping = aes(x = GROSS.AREA,
                           y = TOTAL.VALUE)) + 
  geom_point(aes(size = ROOMS),alpha = 0.4, color = "gray50") +
  geom_point(data = subset(west_old,
                           Re_model == 1 & FULL.BATH > 2 & LIVING.AREA > 2000), color = "green3") +
  scale_x_log10(labels=scales::comma) +
  geom_smooth(method="loess", color = "skyblue3") + 
  labs(title = "Filtered: Remodeled | # of Bathrooms > 2 | Living Area > 2000 sqft") +
  theme(plot.title = element_text(size = 8, face = "bold", colour = "green3"))
ggplotly(p3)





```
